version: '3'

services:

  app:
    build:
      context: .
      dockerfile: etc/dev/docker/server/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_URL: redis:6379
    networks:
      - backend
    volumes:
      - ./:/app

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    networks:
      - backend

networks:
  backend: