version: '3'

services:

  app:
    build:
      context: .
      dockerfile: etc/dev/docker/server/Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - ./:/app
    environment:
      - TODOAPI_NAME=TODOAPI
      - TODOAPI_HOST=
      - TODOAPI_PORT=3000

networks:
  backend: